name: Anaconda Publish

on:
  release:
    types: [published]

jobs:

  publish:
    name: publish / python-3.7 / ubuntu-latest
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: spec2vec-build
          auto-update-conda: true
          environment-file: conda/environment-build.yml
          python-version: "3.7"
      - name: Show conda config
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - name: Build the conda package
        shell: bash -l {0}
        run: |
          conda config --set anaconda_upload no
          export BUILD_FOLDER=/tmp/spec2vec/_build
          mkdir -p $BUILD_FOLDER
          conda build --no-include-recipe \
            --channel bioconda \
            --channel conda-forge \
            --croot $BUILD_FOLDER \
            ./conda
      - name: Push the package to anaconda cloud
        shell: bash -l {0}
        run: |
          export BUILD_FOLDER=/tmp/spec2vec/_build
          anaconda --token ${{ secrets.ANACONDA_TOKEN }} upload --user nlesc --force $BUILD_FOLDER/noarch/*.tar.bz2

  verify:
    name: verify / python-${{ matrix.python-version }} / ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ["3.7"]
    runs-on: ${{ matrix.os }}
    needs: publish
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: spec2vec-test
          auto-update-conda: true
          python-version: "3.7"
      - name: Show conda config
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
      - name: Install the conda package from anaconda repository
        run: |
          conda install --channel bioconda --channel conda-forge --channel nlesc spec2vec
      - name: List conda packages
        run: |
          conda list
      - name: Install dev dependencies to run the tests
        run: |
          conda env update --name spec2vec-test --file conda/environment-dev.yml
          conda info
          conda list
      - name: Run tests after installing the package
        shell: bash -l {0}
        run: |
          export TESTDIR=$RUNNER_TEMP/spec2vec/_test
          [ "$RUNNING_OS" = "Windows" ] && export TESTDIR=$RUNNER_TEMP\\spec2vec\\_test\\
          mkdir -p $TESTDIR
          cp -iRv tests integration-tests $TESTDIR
          cd $TESTDIR
          pytest --ignore="tests/test_version_string_consistency.py"
